name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_GITHUB }}
          publish_dir: ./  # Assuming your content is in the root directory
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
