name: Update File Paths

on:
  push:
    branches:
      - main

jobs:
  update-paths:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust the version if needed

    - name: Install dependencies
      run: |
        npm install

    - name: Run update script
      run: |
        node update_paths.js # Name of your Node.js script
