name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # The branch you push to, which triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_GITHUB }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # The branch where your site will be deployed
          publish_dir: ./  # The directory to publish, adjust if needed
