name: Link Check

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Linkinator
      uses: JustinBeckwith/linkinator-action@v1.10.4
      with:
        # Ensure the path matches the location of your HTML files
        paths: '**/*.html'
        # Additional configuration options can be added here if needed
