name: Update File Paths

on:
  push:
    branches:
      - main

jobs:
  update-paths:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        # No dependencies are needed for this script

    - name: Run update script
      run: |
        python update_paths.py
